### ISSUE TITLE
Add more pictures/description of the physical installation

### ISSUE THREAD

**Issue by bjornbak** [frodef/nilan-cts600-homeassistant#10]
We got a VP18 from 2012 with CTS 600.

I understand that the modbus adapter needs to go in the control panel - not the VP18 itself?

Our control panel is sitting in the middle of a wall in the living room.

Zero WAF if the installation requires extra boxes and/or wires across the wall.

Could you please share some pictures and descriptions of your physcial installation?

Do you have any experience with WiFi modbus adapters?

And whether is room inside the control panel box?

**Comment by bjornbak** [comment]
Just saw @frodef's answer to https://www.facebook.com/groups/667765647316443/posts/1552676995491966/?__cft__[0]=AZWma3XMAkHEq0wVEHjOEk_OB687r9Za9zjRVX0r210R0Xg1BRV0CvofOdxnwrQG1DTHJSUUiNOIiqdG_CSz_hVXPOzVJq3EuDNp0A9WkCAgAtKgTHG6CFEzOarMWd6DvZWPSuvrSzB_frhnUo4Ty6gnBSR6o7dL3ASYFQFQaYEbcvVjUwsVpqmEhVwfAg_nlEGyGocw7Ye2173FwLx_HTjk&__tn__=%2CO%2CP-R and now I'm even more confused...

This setup replaces the control panel with buttons in HA, right?
So I disconnect the original electronics in the control panel and connect the modbus adapter instead?
This is why we need to replace the room temperature sensor in control panel with a HA entity, right? 

So in my case what I need is a Wifi modbus adapter and potentially a power regulator from the 12V to the adapter requirement.
And if I cramp both into the control panel box my wife would notice any difference (except an empty display window and it's now (HA) app controlled.

Adding a temperature sensor updating the HA sensor would be an extra bonus...

**Comment by frodef** [comment]
Hello, sorry for the late answer. Yes the modbus adapter exactly replaces the control panel, in terms of how it is connected to the HVAC unit. It also needs to be connected to your HA machine, and currently only USB is supported for this.

While the control panel is usually put on the wall somewhere, you probably want the modbus/RS485 adapter hidden away in the attic or technical room somewhere. Again, it needs to be connected both to the hvac and the HA machine.

I have this all hidden away in the attic, so the WAF is quite good. Hope this helps.
