### ISSUE TITLE
test on VP18 M2 EK

### ISSUE THREAD

**Issue by Wigalos** [frodef/nilan-cts600-homeassistant#4]
I tested it on my VP18 M2 EK via a virtual machine with home assistant and it worked as long as the control values ​​were the same. It would be interesting to be able to control other values ​​such as supply air temperature min/max, cooling offset temp, hot water electric SUP, ...
The displayed values look good:

![Values](https://github.com/frodef/nilan-cts600-homeassistant/assets/142971431/00d40f09-a3c6-4ac5-a19d-f929b558967d)

But as the creator described, it is a different model and needs to be adjusted a bit. I'll try to adapt it myself, if I run into any specific problems I'll come back.

**Comment by frodef** [comment]
Ok, let me/us know if you have any questions.
