### ISSUE TITLE
Sensors no more available after update Home Assistant to 2024.1 also 2024.1.1

### ISSUE THREAD

**Issue by Guddy87** [frodef/nilan-cts600-homeassistant#5]
My whole infos are in the Titel. If you need any addidtional informations ibwill try to help

**Comment by frodef** [comment]
I'm seeing the same thing here. I'll look into it asap, hopefully tomorrow.

**Comment by Guddy87** [comment]
Many thanks. If you need something i will try to help.

**Comment by frodef** [comment]
I have checked in a fix to this issue. However there's still an issue with detecting sensors that I'll try to resolve before making a new release.

**Comment by Guddy87** [comment]
Hi. Thanks. I do not see the fix but is it the new sensor.py file?. Should i replace it?

**Comment by frodef** [comment]
Yes, that's right.

**Comment by Guddy87** [comment]
It is working your fix. Thanks

**Comment by Guddy87** [comment]
I do not know if it has a dependency but in the clima control i do not see the current status like heating/standby/cooling. I see only the mode heating/off/cooling. If the nilan is in heating mode and stand on 22c but in the room it has 25c in the past i see on the clima control Standby (in german it was  "Untätig"). And when the temperatur are 21c the nilan start heating and in the climacontrol i see heating (gernan"heizen"). Now is see only the mode eacen if its heat or not. Did you change this or is it a new bug with the new haos?

**Comment by frodef** [comment]
I don't see what you describe here. The climate control says "heating" (and changes to a "hot" color) when the cts600.status is "HEATING" and the cts600.led is "On", and the climate control says "Idle" if led.cts600 is "Off", etc.

What is your ventilation unit? Could you check the HA debug log?

**Comment by Guddy87** [comment]
Hi. I have a cts 600 VPL15. I foud why. The led says blinking and thenni see  i have a filter alert. I have reset it and now it is working again. Thanks

**Comment by frodef** [comment]
Oh ok. There should probably be some sort of proper handling of CTS600 alerts.
