### ISSUE TITLE
Missing display and LED controls in HA

### ISSUE THREAD

**Issue by Nicolai96dk** [frodef/nilan-cts600-homeassistant#6]
Hi Frode. I just installed this integration and the climate control seems to be working perfectly! Awesome work!

I’m just missing the LED and display controls. Any idea why? I’ve disconnected the display from the ventilation unit and hooked up the a+b wires to the usb to HA. 
The ventilation unit is a Lindab LVAM 300 (with nilan CTS600)

![image](https://github.com/frodef/nilan-cts600-homeassistant/assets/150072677/413d5021-502e-4d5b-ba93-a93f35eb5ebe)

**Comment by frodef** [comment]
Nice, I didn't know there were non-Nilan units with the CTS600.

The LED is not a "control" but rather a "sensor" entity. From your photo it seems to me you get no sensors at all, is that true?

For my Nilan VPL15 I get 15 sensors including the LED, flow speed and various temperature sensors.

Would you be able to turn on HA debug logging for the CTS600 and see if there are some interesting messages as HA starts up?

**Comment by Nicolai96dk** [comment]
I see some interesting messages in the log but I am unsure what they mean.[](url)
[Nilan.log](https://github.com/frodef/nilan-cts600-homeassistant/files/13964323/Nilan.log)

**Comment by frodef** [comment]
From your log it looks like this is the same as issue #5. Could you see if there's an update available through HACS and if that update helps?

**Comment by Nicolai96dk** [comment]
No update was available in HACS. But I switched from version '2023-09-11' to 'main' (fafbe6e) version and that fixed the problem. Now it wants to update again though.

**Comment by frodef** [comment]
Right, I'll try and make a proper release version soon.
