### ISSUE TITLE
Using fan control in automization?

### ISSUE THREAD

**Issue by Strubu** [frodef/nilan-cts600-homeassistant#7]
Hi, 

First of all thank you for this integration. This is really helping me out!

Is there a possibility to use the fan speed in the atomization pane? Right now, I am only seeing this:
![nilan](https://github.com/frodef/nilan-cts600-homeassistant/assets/10593728/3e1ebac5-dd25-4e89-8094-4df1617272cc)

I can change the fan speed when I click the "more information" button, but not on the dashboard. Any way to fix that?

Again, thank you for your awesome work. :)

**Comment by frodef** [comment]
It is indeed possible, I myself have an automation that increases the fan speed when a humidity sensor detects someone taking a shower.

Use the "Call a service" action, and use the service "Climate: set fan mode".
