### ISSUE TITLE
Connection via Waveshare rs485 to Wifi possible?

### ISSUE THREAD

**Issue by Lutehi-Gregor** [frodef/nilan-cts600-homeassistant#8]
Dear developer
In my search for suitable software for Nilan and a CTS600 controller, I found your application.
Unfortunately, I do not have the possibility to pull a USB cable from the RS485 [interface ](https://www.waveshare.com/wiki/RS485_TO_WIFI/ETH)to the hassio control centre.
I have therefore organised an RS485 to Wifi transmitter.
Can you explain to me how I can store the IP address of the RS485 interface in your software instead of the USB input?
Thank you very much in advance for your support.
Kind regards
Gregor Lüthi

**Comment by frodef** [comment]
Hi, sorry but this is currently not possible. I have been thinking that really this integration should attach itself to a standard HA modbus device (which deal with TCP interfaces properly). However there could be some problems with this because the CTS600 doesn't use proper modbus, so really it needs access to the rs485 layer.

**Comment by Lutehi-Gregor** [comment]
Thank you for the quick reply.
Current means - you could develop it.
I have the RS485 interface here. See the link: [](https://www.waveshare.com/wiki/RS485_TO_WIFI/ETH)
The only thing missing is the corresponding software.
I would be happy to help with the field testing of the interface. But I need support with the software.
I am already looking forward to your reply.

**Comment by Lutehi-Gregor** [comment]
OK, USB works LAN or WLAN does not work.
Currently incomprehensible to me.
Why should the waveshare not work.
It emulates RS485 to the following protocols around TCP / UDP / ARP / ICMP / DHCP / DNS / HTTP / MQTT.
But I can see that my idea of making our ventilation system smart is going to be a bigger challenge than I thought.

**Comment by Lutehi-Gregor** [comment]
Good evening
In the meantime, I have organised a USB to RS485 adapter.
However, when installing the application, it hangs.
Are you aware of this?
Thank you in advance for your support.

**Comment by frodef** [comment]
Could you give some more details about what happens when it hangs? What exactly is "the application"? Could you provide a debug log?

**Comment by Lutehi-Gregor** [comment]
Hello and I apologise for my late response.
In the meantime, I have reinstalled the integration and miraculously it is now working.
After the initial joy, there are of course already desires that would be practical.
In the hope that these can be realised, I would be happy to list them.
1. The original control unit has a traffic jam LED which also indicates when the filters need to be changed during ventilation.
Is it possible to emulate this LED?
2. The physical buttons on the control unit are already there. Is it also possible to integrate the LCD display?
Thank you very much in advance for your support and the great integration of Nilan.

**Comment by frodef** [comment]
Good to hear it works!

1. This might be possible, but I've never seen or heard of such a LED so I'm not sure how it might be done. What is the type of ventilation device you have? Also perhaps a (link to) a picture of the control unit?
2. The LCD should already be emulated (although if you have a very different unit, as per pt 1, there might be some incompatibility). The entity should be named something like sensor.cts600_display

**Comment by Lutehi-Gregor** [comment]
Good evening
Thank you for the quick response. I am happy to provide you with some information about our control system.
It is a Nilan Comfort 600 ventilation system, please see the link below: https://www.nilan.at/produkte/luftung/mit-passiver-warmeruckgewinnung/comfort-600
The ventilation is operated with a cts 600 control unit which can be operated via the corresponding CTS control panel. 
You can find the corresponding instructions as a PDF under the following link. https://eu-data.manualslib.com/pdf/de/pdf7/33/3260/325907-nilan/cts_600.pdf?9fc31b9bd898fc6bc1a5ce7a627f9502
If you require a different language, please let me know.
Regarding LCD display.
When searching through my entities, I can only find the pushbuttons and the climate control panel shown in the photo.
Hope this helps. Thank you in advance for your support.
![entity ](https://github.com/frodef/nilan-cts600-homeassistant/assets/61920830/cc7dfd3c-2423-45b3-bf3d-b30d54218b1a)

**Comment by frodef** [comment]
That is the same controller as I have, and like the display the LED should also be emulated. There must be something different about the Comfort 600 (I have a VPL15) that breaks something.

Could you enable debug logging for this integration and provide me with a startup log?

**Comment by Lutehi-Gregor** [comment]
Thank you for the quick reply.
As it's the same control unit, I'm not giving up all hope just yet.
In the meantime, I have been able to create a log of the Nilan integration.
This can be found in the attached documents.
Now I hope you can use this information to find out the difference to your application and adapt the code accordingly. So that it also works for the Comfort 600.
If you need further information, I will be happy to provide it.
[home-assistant_nilan_cts600_2024-02-17T08-25-40.092Z.log](https://github.com/frodef/nilan-cts600-homeassistant/files/14318195/home-assistant_nilan_cts600_2024-02-17T08-25-40.092Z.log)

**Comment by frodef** [comment]
Thanks for the log. It seems the problem was a bug (or actually the HA API changed) that was fixed some time ago. The fault was mine, however, for not making a proper release.

Please update this integration to release-2024-02-22 and it should hopefully work better.

**Comment by Lutehi-Gregor** [comment]
Good evening and thank you very much for your support. I can hardly believe it, but now everything works via hassio and I can operate the ventilation remotely or create automations with the room sensors.
The next step is to create suitable buttons. But the important thing is that the controls work.
Many thanks again.
